#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : ffmpeg
Version  : 4.4
Release  : 18
URL      : file:///aot/build/clearlinux/packages/ffmpeg/ffmpeg-v4.4.tar.gz
Source0  : file:///aot/build/clearlinux/packages/ffmpeg/ffmpeg-v4.4.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 GPL-3.0
BuildRequires : Cython
BuildRequires : Cython-python
BuildRequires : ImageMagick
BuildRequires : ImageMagick-dev
BuildRequires : LuaJIT
BuildRequires : LuaJIT-dev
BuildRequires : LuaJIT-staticdev
BuildRequires : PyYAML
BuildRequires : Pygments
BuildRequires : SDL2
BuildRequires : SDL2-dev
BuildRequires : SDL2-staticdev
BuildRequires : SVT-AV1-bin
BuildRequires : SVT-AV1-dev
BuildRequires : SVT-AV1-staticdev
BuildRequires : SVT-HEVC-dev
BuildRequires : SVT-HEVC-staticdev
BuildRequires : Sphinx
BuildRequires : VTK
BuildRequires : VTK-dev
BuildRequires : Vulkan-Headers
BuildRequires : Vulkan-Headers-dev
BuildRequires : Vulkan-Loader
BuildRequires : Vulkan-Loader-dev
BuildRequires : Vulkan-Tools
BuildRequires : Vulkan-ValidationLayers
BuildRequires : Z3-dev
BuildRequires : Z3-staticdev
BuildRequires : acl
BuildRequires : acl-dev
BuildRequires : acl-staticdev
BuildRequires : ade-dev
BuildRequires : alsa-firmware
BuildRequires : alsa-lib-dev
BuildRequires : alsa-lib-lib
BuildRequires : alsa-plugins
BuildRequires : alsa-plugins-lib
BuildRequires : alsa-tools
BuildRequires : alsa-ucm-conf
BuildRequires : alsa-utils
BuildRequires : asciidoctor-dev
BuildRequires : beautifulsoup4
BuildRequires : binutils
BuildRequires : binutils-dev
BuildRequires : binutils-staticdev
BuildRequires : brotli
BuildRequires : brotli-dev
BuildRequires : brotli-staticdev
BuildRequires : buildreq-cmake
BuildRequires : buildreq-configure
BuildRequires : buildreq-distutils3
BuildRequires : buildreq-qmake
BuildRequires : bzip2
BuildRequires : bzip2-dev
BuildRequires : bzip2-staticdev
BuildRequires : ca-certs
BuildRequires : ca-certs-static
BuildRequires : cairo
BuildRequires : cairo-dev
BuildRequires : cairo-lib
BuildRequires : cmake
BuildRequires : compat-gcc-10
BuildRequires : compat-gcc-10-dev
BuildRequires : curl-dev
BuildRequires : dav1d-dev
BuildRequires : dav1d-staticdev
BuildRequires : dbus
BuildRequires : dbus-broker
BuildRequires : dbus-dev
BuildRequires : dbus-glib
BuildRequires : dbus-glib-dev
BuildRequires : dbus-python
BuildRequires : doxygen
BuildRequires : e2fsprogs-dev
BuildRequires : eigen
BuildRequires : eigen-data
BuildRequires : eigen-dev
BuildRequires : elfutils-dev
BuildRequires : evtest
BuildRequires : expat-dev
BuildRequires : expat-staticdev
BuildRequires : fftw-dev
BuildRequires : fftw-staticdev
BuildRequires : findutils
BuildRequires : flac
BuildRequires : flac-dev
BuildRequires : flac-staticdev
BuildRequires : fontconfig-data
BuildRequires : fontconfig-dev
BuildRequires : fontconfig-lib
BuildRequires : fontconfig-staticdev
BuildRequires : freetype-dev
BuildRequires : freetype-lib
BuildRequires : freetype-staticdev
BuildRequires : fribidi-dev
BuildRequires : fribidi-staticdev
BuildRequires : gcc
BuildRequires : gcc-dev
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libs-math
BuildRequires : gcc-libstdc++32
BuildRequires : gcc-libubsan
BuildRequires : gcc-locale
BuildRequires : gdb
BuildRequires : gdb-dev
BuildRequires : gettext
BuildRequires : glib
BuildRequires : glib-bin
BuildRequires : glib-data
BuildRequires : glib-dev
BuildRequires : glib-dev32
BuildRequires : glib-lib
BuildRequires : glib-staticdev
BuildRequires : glibc
BuildRequires : glibc-dev
BuildRequires : glibc-dev32
BuildRequires : glibc-lib-avx2
BuildRequires : glibc-libc32
BuildRequires : glibc-staticdev
BuildRequires : glog
BuildRequires : glog-dev
BuildRequires : glu
BuildRequires : glu-dev
BuildRequires : gmp
BuildRequires : gmp-dev
BuildRequires : gmp-staticdev
BuildRequires : gnutls
BuildRequires : gnutls-dev
BuildRequires : googletest
BuildRequires : googletest-dev
BuildRequires : graphite
BuildRequires : graphite-dev
BuildRequires : graphite-staticdev
BuildRequires : gsm
BuildRequires : gsm-dev
BuildRequires : gsm-staticdev
BuildRequires : gstreamer-dev
BuildRequires : gtk+-data
BuildRequires : gtk+-lib
BuildRequires : gtk3-dev
BuildRequires : gtk3-lib
BuildRequires : gtk4
BuildRequires : gtk4-dev
BuildRequires : gtk4-lib
BuildRequires : h5py
BuildRequires : harfbuzz-dev
BuildRequires : harfbuzz-lib
BuildRequires : harfbuzz-staticdev
BuildRequires : hdf5
BuildRequires : hdf5-dev
BuildRequires : hdf5-staticdev
BuildRequires : icu4c-dev
BuildRequires : icu4c-lib
BuildRequires : json-c-staticdev
BuildRequires : jsoncpp
BuildRequires : jsoncpp-dev
BuildRequires : jsoncpp-lib
BuildRequires : jsoncpp-staticdev
BuildRequires : keyutils
BuildRequires : keyutils-dev
BuildRequires : krb5
BuildRequires : krb5-dev
BuildRequires : l-smash-dev
BuildRequires : l-smash-staticdev
BuildRequires : ladspa_sdk
BuildRequires : ladspa_sdk-bin
BuildRequires : ladspa_sdk-dev
BuildRequires : ladspa_sdk-staticdev
BuildRequires : lcms2
BuildRequires : lcms2-dev
BuildRequires : lcms2-staticdev
BuildRequires : libICE-dev
BuildRequires : libSM-dev
BuildRequires : libX11-data
BuildRequires : libX11-dev
BuildRequires : libX11-lib
BuildRequires : libXScrnSaver
BuildRequires : libXScrnSaver-dev
BuildRequires : libXScrnSaver-lib
BuildRequires : libXau-dev
BuildRequires : libXau-lib
BuildRequires : libXcursor-dev
BuildRequires : libXcursor-lib
BuildRequires : libXdamage-dev
BuildRequires : libXdamage-lib
BuildRequires : libXdmcp-dev
BuildRequires : libXdmcp-lib
BuildRequires : libXext-dev
BuildRequires : libXext-lib
BuildRequires : libXfont2-dev
BuildRequires : libXft-dev
BuildRequires : libXft-lib
BuildRequires : libXi-dev
BuildRequires : libXi-lib
BuildRequires : libXrender-dev
BuildRequires : libXrender-lib
BuildRequires : libXtst-dev
BuildRequires : libXtst-lib
BuildRequires : libXxf86vm-dev
BuildRequires : libXxf86vm-lib
BuildRequires : libaom-dev
BuildRequires : libaom-staticdev
BuildRequires : libarchive
BuildRequires : libarchive-dev
BuildRequires : libarchive-staticdev
BuildRequires : libass-dev
BuildRequires : libass-lib
BuildRequires : libass-staticdev
BuildRequires : libatomic_ops-dev
BuildRequires : libatomic_ops-staticdev
BuildRequires : libbluray-dev
BuildRequires : libbluray-staticdev
BuildRequires : libcap
BuildRequires : libcap-dev
BuildRequires : libcap-ng-dev
BuildRequires : libconfig-dev
BuildRequires : libconfig-staticdev
BuildRequires : libdrm
BuildRequires : libdrm-dev
BuildRequires : libdrm-lib
BuildRequires : libdrm-staticdev
BuildRequires : libdvdnav
BuildRequires : libdvdnav-dev
BuildRequires : libdvdnav-staticdev
BuildRequires : libdvdread
BuildRequires : libdvdread-dev
BuildRequires : libdvdread-staticdev
BuildRequires : libedit
BuildRequires : libedit-dev
BuildRequires : libepoxy
BuildRequires : libepoxy-dev
BuildRequires : libepoxy-staticdev
BuildRequires : libfdk_aac-dev
BuildRequires : libfdk_aac-staticdev
BuildRequires : libffi
BuildRequires : libffi-dev
BuildRequires : libffi-staticdev
BuildRequires : libgcc1
BuildRequires : libgcrypt
BuildRequires : libgcrypt-dev
BuildRequires : libgpg-error
BuildRequires : libgpg-error-dev
BuildRequires : libgphoto2-dev
BuildRequires : libidn2
BuildRequires : libidn2-dev
BuildRequires : libidn2-staticdev
BuildRequires : libinput-data
BuildRequires : libinput-dev
BuildRequires : libinput-lib
BuildRequires : libinput-libexec
BuildRequires : libjpeg-turbo-dev
BuildRequires : libjpeg-turbo-staticdev
BuildRequires : libmp3lame-dev
BuildRequires : libmp3lame-lib
BuildRequires : libmp3lame-staticdev
BuildRequires : libogg
BuildRequires : libogg-dev
BuildRequires : libogg-staticdev
BuildRequires : libpciaccess
BuildRequires : libpciaccess-dev
BuildRequires : libplacebo
BuildRequires : libplacebo-dev
BuildRequires : libplacebo-staticdev
BuildRequires : libpng
BuildRequires : libpng-dev
BuildRequires : libpng-lib
BuildRequires : libpng-staticdev
BuildRequires : librsvg-bin
BuildRequires : librsvg-data
BuildRequires : librsvg-dev
BuildRequires : librsvg-lib
BuildRequires : librsvg-staticdev
BuildRequires : libsamplerate
BuildRequires : libsamplerate-dev
BuildRequires : libsamplerate-staticdev
BuildRequires : libsndfile
BuildRequires : libsndfile-dev
BuildRequires : libsndfile-staticdev
BuildRequires : libsrt-dev
BuildRequires : libsrt-staticdev
BuildRequires : libstdc++
BuildRequires : libstdc++-dev
BuildRequires : libtasn1-dev
BuildRequires : libtasn1-staticdev
BuildRequires : libtheora-dev
BuildRequires : libtheora-staticdev
BuildRequires : libudfread-dev
BuildRequires : libudfread-staticdev
BuildRequires : libunistring-dev
BuildRequires : libunistring-staticdev
BuildRequires : libunwind
BuildRequires : libunwind-dev
BuildRequires : libusb
BuildRequires : libusb-dev
BuildRequires : libva
BuildRequires : libva-dev
BuildRequires : libva-intel-driver
BuildRequires : libva-lib
BuildRequires : libvapoursynth
BuildRequires : libvapoursynth-bin
BuildRequires : libvapoursynth-dev
BuildRequires : libvapoursynth-python
BuildRequires : libvapoursynth-python3
BuildRequires : libvapoursynth-staticdev
BuildRequires : libvdpau
BuildRequires : libvdpau-dev
BuildRequires : libvorbis
BuildRequires : libvorbis-dev
BuildRequires : libvorbis-staticdev
BuildRequires : libvpx-dev
BuildRequires : libvpx-staticdev
BuildRequires : libwebp
BuildRequires : libwebp-dev
BuildRequires : libwebp-staticdev
BuildRequires : libx264-dev
BuildRequires : libx264-staticdev
BuildRequires : libx265
BuildRequires : libx265-dev
BuildRequires : libx265-staticdev
BuildRequires : libxcb-dev
BuildRequires : libxcb-lib
BuildRequires : libxkbcommon
BuildRequires : libxkbcommon-dev
BuildRequires : libxml2-dev
BuildRequires : libxml2-staticdev
BuildRequires : libxslt-bin
BuildRequires : libxslt-dev
BuildRequires : libxslt-staticdev
BuildRequires : libxvid
BuildRequires : libxvid-dev
BuildRequires : libxvid-staticdev
BuildRequires : libzimg-dev
BuildRequires : libzimg-staticdev
BuildRequires : lrzip-dev
BuildRequires : lrzip-staticdev
BuildRequires : lz4
BuildRequires : lz4-dev
BuildRequires : lz4-staticdev
BuildRequires : lzo
BuildRequires : lzo-dev
BuildRequires : lzo-staticdev
BuildRequires : md4c
BuildRequires : md4c-dev
BuildRequires : md4c-staticdev
BuildRequires : mediasdk-dev
BuildRequires : mesa
BuildRequires : mesa-demos
BuildRequires : mesa-dev
BuildRequires : mesa-lib
BuildRequires : mm-common-dev
BuildRequires : nasm
BuildRequires : nasm-bin
BuildRequires : ncurses-dev
BuildRequires : nettle
BuildRequires : nettle-dev
BuildRequires : nettle-staticdev
BuildRequires : ninja
BuildRequires : not-ffmpeg
BuildRequires : not-ffmpeg-dev
BuildRequires : numlockx
BuildRequires : numpy
BuildRequires : numpy-dev
BuildRequires : numpy-stl
BuildRequires : nv-codec-headers
BuildRequires : nv-codec-headers-dev
BuildRequires : ocl-icd-dev
BuildRequires : onemkl
BuildRequires : onemkl-dev
BuildRequires : onemkl-lib
BuildRequires : openblas
BuildRequires : openblas-dev
BuildRequires : openblas-staticdev
BuildRequires : opencl-headers
BuildRequires : opencl-headers-data
BuildRequires : opencl-headers-debuginfo
BuildRequires : opencl-headers-dev
BuildRequires : opencv
BuildRequires : opencv-bin
BuildRequires : opencv-data
BuildRequires : opencv-dev
BuildRequires : opencv-python
BuildRequires : opencv-python3
BuildRequires : opencv-staticdev
BuildRequires : openjdk13
BuildRequires : openjdk13-dev
BuildRequires : openjpeg-dev
BuildRequires : openjpeg-staticdev
BuildRequires : openssl
BuildRequires : openssl-dev
BuildRequires : openssl-lib
BuildRequires : openssl-staticdev
BuildRequires : opus-dev
BuildRequires : opus-staticdev
BuildRequires : orc-dev
BuildRequires : orc-staticdev
BuildRequires : p11-kit
BuildRequires : p11-kit-dev
BuildRequires : pacrunner
BuildRequires : pacrunner-dev
BuildRequires : pango-lib
BuildRequires : pcre-dev
BuildRequires : pcre-staticdev
BuildRequires : pcre2-dev
BuildRequires : pcre2-staticdev
BuildRequires : perl
BuildRequires : perl(XML::Parser)
BuildRequires : perl-Config-General
BuildRequires : perl-Config-Tiny
BuildRequires : perl-Crypt-SSLeay
BuildRequires : perl-DBI
BuildRequires : perl-DateTime-TimeZone
BuildRequires : perl-Encode-Locale
BuildRequires : perl-Error
BuildRequires : perl-File-Listing
BuildRequires : perl-HTML-Parser
BuildRequires : perl-HTML-Tagset
BuildRequires : perl-HTTP-Cookies
BuildRequires : perl-HTTP-Date
BuildRequires : perl-HTTP-Message
BuildRequires : perl-HTTP-Negotiate
BuildRequires : perl-IO-HTML
BuildRequires : perl-LWP-MediaTypes
BuildRequires : perl-LWP-Protocol-https
BuildRequires : perl-Params-Validate
BuildRequires : perl-Test-Simple
BuildRequires : perl-Try-Tiny
BuildRequires : perl-URI
BuildRequires : perl-XML-NamespaceSupport
BuildRequires : perl-XML-Parser
BuildRequires : perl-libwww-perl
BuildRequires : perl-man
BuildRequires : pip
BuildRequires : pixman
BuildRequires : pixman-dev
BuildRequires : pixman-lib
BuildRequires : pixman-staticdev
BuildRequires : pkg-config
BuildRequires : pkg-config-dev
BuildRequires : pkgconfig(Magick++)
BuildRequires : pkgconfig(MagickCore)
BuildRequires : pkgconfig(MagickWand)
BuildRequires : pkgconfig(SvtAv1Dec)
BuildRequires : pkgconfig(SvtAv1Enc)
BuildRequires : pkgconfig(SvtHevcEnc)
BuildRequires : pkgconfig(alsa)
BuildRequires : pkgconfig(alsa-topology)
BuildRequires : pkgconfig(aom)
BuildRequires : pkgconfig(atomic_ops)
BuildRequires : pkgconfig(blkid)
BuildRequires : pkgconfig(bzip2)
BuildRequires : pkgconfig(cairo)
BuildRequires : pkgconfig(cairo-egl)
BuildRequires : pkgconfig(cairo-fc)
BuildRequires : pkgconfig(cairo-ft)
BuildRequires : pkgconfig(cairo-gl)
BuildRequires : pkgconfig(cairo-glx)
BuildRequires : pkgconfig(cairo-gobject)
BuildRequires : pkgconfig(cairo-pdf)
BuildRequires : pkgconfig(cairo-png)
BuildRequires : pkgconfig(cairo-ps)
BuildRequires : pkgconfig(cairo-script)
BuildRequires : pkgconfig(cairo-svg)
BuildRequires : pkgconfig(cairo-xcb)
BuildRequires : pkgconfig(cairo-xcb-shm)
BuildRequires : pkgconfig(cairo-xlib)
BuildRequires : pkgconfig(cairo-xlib-xcb)
BuildRequires : pkgconfig(cairo-xlib-xrender)
BuildRequires : pkgconfig(dav1d)
BuildRequires : pkgconfig(dbus-1)
BuildRequires : pkgconfig(dri)
BuildRequires : pkgconfig(dri2proto)
BuildRequires : pkgconfig(dri3proto)
BuildRequires : pkgconfig(egl)
BuildRequires : pkgconfig(expat)
BuildRequires : pkgconfig(fdisk)
BuildRequires : pkgconfig(fdk-aac)
BuildRequires : pkgconfig(ffnvcodec)
BuildRequires : pkgconfig(fontconfig)
BuildRequires : pkgconfig(freetype2)
BuildRequires : pkgconfig(fribidi)
BuildRequires : pkgconfig(gbm)
BuildRequires : pkgconfig(gdm)
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(gio-unix-2.0)
BuildRequires : pkgconfig(gl)
BuildRequires : pkgconfig(glesv1_cm)
BuildRequires : pkgconfig(glesv2)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(glu)
BuildRequires : pkgconfig(gmock)
BuildRequires : pkgconfig(gmock_main)
BuildRequires : pkgconfig(gmodule-2.0)
BuildRequires : pkgconfig(gmodule-export-2.0)
BuildRequires : pkgconfig(gmodule-no-export-2.0)
BuildRequires : pkgconfig(gmp)
BuildRequires : pkgconfig(gmpxx)
BuildRequires : pkgconfig(gnutls)
BuildRequires : pkgconfig(gobject-2.0)
BuildRequires : pkgconfig(graphite2)
BuildRequires : pkgconfig(gtest)
BuildRequires : pkgconfig(gtest_main)
BuildRequires : pkgconfig(gthread-2.0)
BuildRequires : pkgconfig(haisrt)
BuildRequires : pkgconfig(hogweed)
BuildRequires : pkgconfig(ibus-1.0)
BuildRequires : pkgconfig(ice)
BuildRequires : pkgconfig(lame)
BuildRequires : pkgconfig(libass)
BuildRequires : pkgconfig(libbluray)
BuildRequires : pkgconfig(libbrotlicommon)
BuildRequires : pkgconfig(libbrotlidec)
BuildRequires : pkgconfig(libbrotlienc)
BuildRequires : pkgconfig(libconfig)
BuildRequires : pkgconfig(libconfig++)
BuildRequires : pkgconfig(libcrypto)
BuildRequires : pkgconfig(libdrm)
BuildRequires : pkgconfig(libdvbv5)
BuildRequires : pkgconfig(libffi)
BuildRequires : pkgconfig(libidn2)
BuildRequires : pkgconfig(libjpeg)
BuildRequires : pkgconfig(libkms)
BuildRequires : pkgconfig(liblsmash)
BuildRequires : pkgconfig(liblzma)
BuildRequires : pkgconfig(libopenjp2)
BuildRequires : pkgconfig(libpcre)
BuildRequires : pkgconfig(libpcre16)
BuildRequires : pkgconfig(libpcre32)
BuildRequires : pkgconfig(libpcrecpp)
BuildRequires : pkgconfig(libpcreposix)
BuildRequires : pkgconfig(libpng)
BuildRequires : pkgconfig(libpulse)
BuildRequires : pkgconfig(libpulse-simple)
BuildRequires : pkgconfig(librtmp)
BuildRequires : pkgconfig(libssl)
BuildRequires : pkgconfig(libsystemd)
BuildRequires : pkgconfig(libtasn1)
BuildRequires : pkgconfig(libturbojpeg)
BuildRequires : pkgconfig(libudev)
BuildRequires : pkgconfig(libudfread)
BuildRequires : pkgconfig(libunistring)
BuildRequires : pkgconfig(libunwind)
BuildRequires : pkgconfig(libunwind-coredump)
BuildRequires : pkgconfig(libunwind-generic)
BuildRequires : pkgconfig(libunwind-ptrace)
BuildRequires : pkgconfig(libunwind-setjmp)
BuildRequires : pkgconfig(libusb-1.0)
BuildRequires : pkgconfig(libva)
BuildRequires : pkgconfig(libwebp)
BuildRequires : pkgconfig(libwebpdecoder)
BuildRequires : pkgconfig(libwebpdemux)
BuildRequires : pkgconfig(libwebpmux)
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : pkgconfig(mm-common-libstdc++)
BuildRequires : pkgconfig(mm-common-util)
BuildRequires : pkgconfig(mount)
BuildRequires : pkgconfig(nettle)
BuildRequires : pkgconfig(ogg)
BuildRequires : pkgconfig(openssl)
BuildRequires : pkgconfig(opus)
BuildRequires : pkgconfig(osmesa)
BuildRequires : pkgconfig(p11-kit-1)
BuildRequires : pkgconfig(pciaccess)
BuildRequires : pkgconfig(pixman-1)
BuildRequires : pkgconfig(presentproto)
BuildRequires : pkgconfig(readline)
BuildRequires : pkgconfig(rubberband)
BuildRequires : pkgconfig(samplerate)
BuildRequires : pkgconfig(sdl2)
BuildRequires : pkgconfig(sm)
BuildRequires : pkgconfig(smartcols)
BuildRequires : pkgconfig(speex)
BuildRequires : pkgconfig(srt)
BuildRequires : pkgconfig(systemd)
BuildRequires : pkgconfig(theora)
BuildRequires : pkgconfig(uuid)
BuildRequires : pkgconfig(vapoursynth)
BuildRequires : pkgconfig(vapoursynth-script)
BuildRequires : pkgconfig(vdpau)
BuildRequires : pkgconfig(vorbis)
BuildRequires : pkgconfig(vpx)
BuildRequires : pkgconfig(vulkan)
BuildRequires : pkgconfig(wayland-client)
BuildRequires : pkgconfig(wayland-cursor)
BuildRequires : pkgconfig(wayland-egl)
BuildRequires : pkgconfig(wayland-protocols)
BuildRequires : pkgconfig(wayland-scanner)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(x11-xcb)
BuildRequires : pkgconfig(x264)
BuildRequires : pkgconfig(x265)
BuildRequires : pkgconfig(xatracker)
BuildRequires : pkgconfig(xcb)
BuildRequires : pkgconfig(xcb-aux)
BuildRequires : pkgconfig(xcb-composite)
BuildRequires : pkgconfig(xcb-damage)
BuildRequires : pkgconfig(xcb-dpms)
BuildRequires : pkgconfig(xcb-dri2)
BuildRequires : pkgconfig(xcb-dri3)
BuildRequires : pkgconfig(xcb-glx)
BuildRequires : pkgconfig(xcb-present)
BuildRequires : pkgconfig(xcb-randr)
BuildRequires : pkgconfig(xcb-record)
BuildRequires : pkgconfig(xcb-render)
BuildRequires : pkgconfig(xcb-res)
BuildRequires : pkgconfig(xcb-screensaver)
BuildRequires : pkgconfig(xcb-shape)
BuildRequires : pkgconfig(xcb-shm)
BuildRequires : pkgconfig(xcb-sync)
BuildRequires : pkgconfig(xcb-xf86dri)
BuildRequires : pkgconfig(xcb-xfixes)
BuildRequires : pkgconfig(xcb-xinerama)
BuildRequires : pkgconfig(xcb-xinput)
BuildRequires : pkgconfig(xcb-xkb)
BuildRequires : pkgconfig(xcb-xtest)
BuildRequires : pkgconfig(xcb-xv)
BuildRequires : pkgconfig(xcb-xvmc)
BuildRequires : pkgconfig(xcomposite)
BuildRequires : pkgconfig(xcursor)
BuildRequires : pkgconfig(xdamage)
BuildRequires : pkgconfig(xdg-desktop-portal)
BuildRequires : pkgconfig(xext)
BuildRequires : pkgconfig(xextproto)
BuildRequires : pkgconfig(xf86driproto)
BuildRequires : pkgconfig(xfixes)
BuildRequires : pkgconfig(xfont)
BuildRequires : pkgconfig(xi)
BuildRequires : pkgconfig(xinerama)
BuildRequires : pkgconfig(xkbcommon)
BuildRequires : pkgconfig(xmu)
BuildRequires : pkgconfig(xorg-macros)
BuildRequires : pkgconfig(xorg-server)
BuildRequires : pkgconfig(xpm)
BuildRequires : pkgconfig(xproto)
BuildRequires : pkgconfig(xrandr)
BuildRequires : pkgconfig(xrender)
BuildRequires : pkgconfig(xscrnsaver)
BuildRequires : pkgconfig(xshmfence)
BuildRequires : pkgconfig(xt)
BuildRequires : pkgconfig(xtst)
BuildRequires : pkgconfig(xvmc)
BuildRequires : pkgconfig(xxf86vm)
BuildRequires : pkgconfig(zimg)
BuildRequires : pkgconfig(zlib)
BuildRequires : pluggy
BuildRequires : procps-ng
BuildRequires : pugixml-dev
BuildRequires : pulseaudio
BuildRequires : pulseaudio-dev
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : python-pkgconfig
BuildRequires : python3-core
BuildRequires : python3-dev
BuildRequires : python3-staticdev
BuildRequires : qca-qt5
BuildRequires : qca-qt5-dev
BuildRequires : qt3d
BuildRequires : qt3d-dev
BuildRequires : qt5ct
BuildRequires : qtbase
BuildRequires : qtbase-dev
BuildRequires : qtbase-extras
BuildRequires : qtcanvas3d
BuildRequires : qtcharts
BuildRequires : qtcharts-dev
BuildRequires : qtconnectivity
BuildRequires : qtconnectivity-dev
BuildRequires : qtdatavis3d
BuildRequires : qtdatavis3d-dev
BuildRequires : qtdeclarative
BuildRequires : qtdeclarative-dev
BuildRequires : qtgamepad
BuildRequires : qtgamepad-dev
BuildRequires : qtgraphicaleffects
BuildRequires : qtimageformats
BuildRequires : qtlocation
BuildRequires : qtlocation-dev
BuildRequires : qtmqtt
BuildRequires : qtmqtt-dev
BuildRequires : qtmultimedia
BuildRequires : qtmultimedia-dev
BuildRequires : qtnetworkauth
BuildRequires : qtnetworkauth-dev
BuildRequires : qtquickcontrols
BuildRequires : qtquickcontrols2
BuildRequires : qtquickcontrols2-dev
BuildRequires : qtremoteobjects-dev
BuildRequires : qtscript
BuildRequires : qtscript-dev
BuildRequires : qtscript-extras
BuildRequires : qtscxml
BuildRequires : qtscxml-dev
BuildRequires : qtsensors
BuildRequires : qtsensors-dev
BuildRequires : qtserialbus
BuildRequires : qtserialbus-dev
BuildRequires : qtserialport
BuildRequires : qtserialport-dev
BuildRequires : qtspeech
BuildRequires : qtspeech-dev
BuildRequires : qtsvg
BuildRequires : qtsvg-dev
BuildRequires : qttools
BuildRequires : qttools-dev
BuildRequires : qttranslations
BuildRequires : qtvirtualkeyboard
BuildRequires : qtvirtualkeyboard-dev
BuildRequires : qtwayland
BuildRequires : qtwayland-dev
BuildRequires : qtwebchannel
BuildRequires : qtwebchannel-dev
BuildRequires : qtwebengine
BuildRequires : qtwebengine-dev
BuildRequires : qtwebsockets
BuildRequires : qtwebsockets-dev
BuildRequires : qtx11extras
BuildRequires : qtx11extras-dev
BuildRequires : qtxmlpatterns
BuildRequires : qtxmlpatterns-dev
BuildRequires : rsync
BuildRequires : rtmpdump
BuildRequires : rtmpdump-dev
BuildRequires : rtmpdump-staticdev
BuildRequires : rubberband-bin
BuildRequires : rubberband-data
BuildRequires : rubberband-dev
BuildRequires : rubberband-lib
BuildRequires : rubberband-staticdev
BuildRequires : sed
BuildRequires : setxkbmap
BuildRequires : shaderc
BuildRequires : shaderc-dev
BuildRequires : shaderc-lib
BuildRequires : shaderc-staticdev
BuildRequires : shared-mime-info
BuildRequires : six
BuildRequires : snappy-dev
BuildRequires : snappy-staticdev
BuildRequires : solid-dev
BuildRequires : sonnet-dev
BuildRequires : speex-dev
BuildRequires : speex-staticdev
BuildRequires : speexdsp-dev
BuildRequires : speexdsp-staticdev
BuildRequires : sqlite-autoconf
BuildRequires : sqlite-autoconf-dev
BuildRequires : sqlite-autoconf-staticdev
BuildRequires : syntax-highlighting
BuildRequires : syntax-highlighting-data
BuildRequires : syntax-highlighting-dev
BuildRequires : syntax-highlighting-lib
BuildRequires : systemd
BuildRequires : systemd-dev
BuildRequires : tbb
BuildRequires : tbb-dev
BuildRequires : tbb-lib
BuildRequires : tesseract
BuildRequires : tesseract-bin
BuildRequires : tesseract-data
BuildRequires : tesseract-dev
BuildRequires : texinfo
BuildRequires : tiff
BuildRequires : tiff-dev
BuildRequires : tiff-staticdev
BuildRequires : tox
BuildRequires : uchardet
BuildRequires : uchardet-dev
BuildRequires : uchardet-staticdev
BuildRequires : util-linux
BuildRequires : util-linux-dev
BuildRequires : util-linux-staticdev
BuildRequires : vamp-sdk
BuildRequires : vamp-sdk-dev
BuildRequires : vamp-sdk-staticdev
BuildRequires : virtualenv
BuildRequires : wayland
BuildRequires : wayland-dev
BuildRequires : weston
BuildRequires : wmctrl
BuildRequires : xauth
BuildRequires : xcb-proto
BuildRequires : xcb-proto-dev
BuildRequires : xcb-util-cursor-dev
BuildRequires : xcb-util-dev
BuildRequires : xcb-util-keysyms-dev
BuildRequires : xcb-util-renderutil-dev
BuildRequires : xcb-util-wm-dev
BuildRequires : xcb-util-xrm-dev
BuildRequires : xclip
BuildRequires : xdg-dbus-proxy
BuildRequires : xdg-desktop-portal
BuildRequires : xdg-desktop-portal-dev
BuildRequires : xdg-desktop-portal-gtk
BuildRequires : xdg-desktop-portal-kde
BuildRequires : xdg-user-dirs
BuildRequires : xdg-user-dirs-gtk
BuildRequires : xdg-utils
BuildRequires : xdotool
BuildRequires : xdpyinfo
BuildRequires : xf86-input-libinput
BuildRequires : xf86-video-amdgpu
BuildRequires : xf86-video-ati
BuildRequires : xf86-video-fbdev
BuildRequires : xf86-video-nouveau
BuildRequires : xf86-video-qxl
BuildRequires : xf86-video-vboxvideo
BuildRequires : xf86-video-vesa
BuildRequires : xf86-video-vmware
BuildRequires : xfontsel
BuildRequires : xhost
BuildRequires : xinit
BuildRequires : xinput
BuildRequires : xkbcomp
BuildRequires : xkeyboard-config
BuildRequires : xkill
BuildRequires : xmodmap
BuildRequires : xorg-server
BuildRequires : xorg-server-dev
BuildRequires : xorgproto
BuildRequires : xorgproto-dev
BuildRequires : xprop
BuildRequires : xrandr
BuildRequires : xrdb
BuildRequires : xrdp
BuildRequires : xrestop
BuildRequires : xscreensaver
BuildRequires : xsel
BuildRequires : xset
BuildRequires : xsetroot
BuildRequires : xvfb-run
BuildRequires : xwd
BuildRequires : xwininfo
BuildRequires : xz
BuildRequires : xz-dev
BuildRequires : xz-staticdev
BuildRequires : yaml-cpp
BuildRequires : yaml-cpp-dev
BuildRequires : zlib
BuildRequires : zlib-dev
BuildRequires : zlib-staticdev
BuildRequires : zstd-dev
BuildRequires : zstd-staticdev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
# Ignore missing build ids
%undefine _missing_build_ids_terminate_build
# Disable automatic requeriments processing
AutoReq: no

%description
SPARC optimizations have been removed in
commit b4dd424d96f09f9bafb88e47f37df65dc4529143
The last revission with the optimizations is fb1b70c1ed50951c5fc1a309c3c446b2eaaf564b

%prep
%setup -q -n ffmpeg
cd %{_builddir}/ffmpeg

%build
unset http_proxy
unset https_proxy
unset no_proxy
export SSL_CERT_FILE=/var/cache/ca-certs/anchors/ca-certificates.crt
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1622807804
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
## altflags_pgo content
## pgo generate
export PGO_GEN="-fprofile-generate=/var/tmp/pgo -fprofile-dir=/var/tmp/pgo -fprofile-abs-path -fprofile-update=atomic -fprofile-arcs -ftest-coverage --coverage -fprofile-partial-training"
export CFLAGS_GENERATE="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -falign-functions=32 -flimit-function-alignment -fno-stack-protector -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -mtls-dialect=gnu2 -fno-math-errno -fno-trapping-math -pipe -ffat-lto-objects -flto=16 -fPIC -Wl,-z,max-page-size=0x1000 -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc -Wl,--build-id=sha1 -fdevirtualize-at-ltrans -Wl,-z,now -Wl,-z,relro -Wl,-sort-common -fasynchronous-unwind-tables $PGO_GEN"
export FCFLAGS_GENERATE="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -falign-functions=32 -flimit-function-alignment -fno-stack-protector -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -mtls-dialect=gnu2 -fno-math-errno -fno-trapping-math -pipe -ffat-lto-objects -flto=16 -fPIC -Wl,-z,max-page-size=0x1000 -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc -Wl,--build-id=sha1 -fdevirtualize-at-ltrans -Wl,-z,now -Wl,-z,relro -Wl,-sort-common -fasynchronous-unwind-tables $PGO_GEN"
export FFLAGS_GENERATE="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -falign-functions=32 -flimit-function-alignment -fno-stack-protector -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -mtls-dialect=gnu2 -fno-math-errno -fno-trapping-math -pipe -ffat-lto-objects -flto=16 -fPIC -Wl,-z,max-page-size=0x1000 -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc -Wl,--build-id=sha1 -fdevirtualize-at-ltrans -Wl,-z,now -Wl,-z,relro -Wl,-sort-common -fasynchronous-unwind-tables $PGO_GEN"
export CXXFLAGS_GENERATE="-std=c++11 -g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -falign-functions=32 -flimit-function-alignment -fno-stack-protector -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -mtls-dialect=gnu2 -fno-math-errno -fno-trapping-math -fvisibility-inlines-hidden -pipe -ffat-lto-objects -flto=16 -fPIC -Wl,-z,max-page-size=0x1000 -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc -Wl,--build-id=sha1 -fdevirtualize-at-ltrans -Wl,-z,now -Wl,-z,relro -Wl,-sort-common -fasynchronous-unwind-tables $PGO_GEN"
export LDFLAGS_GENERATE="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -falign-functions=32 -flimit-function-alignment -fno-stack-protector -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -mtls-dialect=gnu2 -fno-math-errno -fno-trapping-math -pipe -ffat-lto-objects -flto=16 -fPIC -Wl,-z,max-page-size=0x1000 -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc -lpthread -Wl,--build-id=sha1 -fdevirtualize-at-ltrans -Wl,-z,now -Wl,-z,relro -Wl,-sort-common -fasynchronous-unwind-tables $PGO_GEN"
## pgo use
## -ffat-lto-objects -fno-PIE -fno-PIE -m64 -no-pie -fPIC -Wl,-z,max-page-size=0x1000 -fvisibility=hidden -flto-partition=none
## gcc: -feliminate-unused-debug-types -fipa-pta -flto=16 -Wno-error -Wp,-D_REENTRANT -fno-common -funroll-loops
export PGO_USE="-fprofile-use=/var/tmp/pgo -fprofile-dir=/var/tmp/pgo -fprofile-abs-path -fprofile-correction -fprofile-partial-training"
export CFLAGS_USE="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -Wl,-z,max-page-size=0x1000 -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc $PGO_USE"
export FCFLAGS_USE=" -g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -Wl,-z,max-page-size=0x1000 -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc $PGO_USE"
export FFLAGS_USE="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -Wl,-z,max-page-size=0x1000 -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc $PGO_USE"
export CXXFLAGS_USE="-std=c++11 -g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -fvisibility-inlines-hidden -pipe -ffat-lto-objects -fPIC -Wl,-z,max-page-size=0x1000 -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc $PGO_USE"
export LDFLAGS_USE="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -Wl,-z,max-page-size=0x1000 -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc -lpthread $PGO_USE"
#
export AR=/usr/bin/gcc-ar
export RANLIB=/usr/bin/gcc-ranlib
export NM=/usr/bin/gcc-nm
#
export MAKEFLAGS=%{?_smp_mflags}
#
%global _lto_cflags 1
#global _lto_cflags %{nil}
%global _disable_maintainer_mode 1
#%global _disable_maintainer_mode %{nil}
#
export CCACHE_DISABLE=true
#
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/nvidia/lib64:/usr/nvidia/lib64/vdpau:/usr/nvidia/lib64/xorg/modules/drivers:/usr/nvidia/lib64/xorg/modules/extensions:/usr/local/cuda/lib64:/usr/lib64/dri:/usr/lib64/haswell:/usr/lib64:/usr/lib:/usr/share"
#
export LIBRARY_PATH="$LIBRARY_PATH:/usr/nvidia/lib64:/usr/nvidia/lib64/vdpau:/usr/nvidia/lib64/xorg/modules/drivers:/usr/nvidia/lib64/xorg/modules/extensions:/usr/local/cuda/lib64:/usr/lib64/dri:/usr/lib64/haswell:/usr/lib64:/usr/lib:/usr/share"
#
export PATH="$PATH:/usr/local/cuda/bin:/usr/nvidia/bin:/usr/bin/haswell:/usr/bin:/usr/sbin"
#
#export CPATH="$CPATH:/usr/local/cuda/include"
#
## altflags_pgo end
if [ ! -f statuspgo ]; then
echo PGO Phase 1
export CFLAGS="${CFLAGS_GENERATE}"
export CXXFLAGS="${CXXFLAGS_GENERATE}"
export FFLAGS="${FFLAGS_GENERATE}"
export FCFLAGS="${FCFLAGS_GENERATE}"
export LDFLAGS="${LDFLAGS_GENERATE}"
./configure \
    --prefix=/usr \
    --libdir=/usr/lib64 \
    --pkg-config-flags="--static" \
    --ar="/usr/bin/gcc-ar" \
    --nm="/usr/bin/gcc-nm" \
    --ranlib="/usr/bin/gcc-ranlib" \
    --cc=/usr/bin/gcc \
    --cxx=/usr/bin/g++ \
    --disable-shared \
    --disable-debug \
    --disable-avx512 \
    --disable-podpages \
    --disable-stripping \
    --disable-gnutls \
    --disable-runtime-cpudetect \
    --disable-libjack \
    --disable-cuda-llvm \
    --disable-libmfx \
    --disable-libv4l2 \
    --disable-libopencv \
    --cpu=native \
    --enable-optimizations \
    --enable-avx2 \
    --enable-doc \
    --enable-htmlpages \
    --enable-manpages \
    --enable-txtpages \
    --enable-static \
    --enable-pic \
    --enable-lto \
    --enable-libpulse \
    --enable-asm \
    --enable-pthreads \
    --enable-gpl \
    --enable-version3 \
    --enable-nonfree \
    --enable-hardcoded-tables \
    --enable-sdl2 \
    --enable-outdev=sdl2 \
    --enable-avcodec \
    --enable-avdevice \
    --enable-avfilter \
    --enable-avformat \
    --enable-avutil \
    --enable-dct \
    --enable-dwt \
    --enable-lsp \
    --enable-lzo \
    --enable-mdct \
    --enable-rdft \
    --enable-fft \
    --enable-faan \
    --enable-pixelutils \
    --enable-bzlib \
    --enable-cuda \
    --enable-cuda-nvcc \
    --enable-cuvid \
    --enable-error-resilience \
    --disable-safe-bitstream-reader \
    --enable-ffmpeg \
    --enable-ffnvcodec \
    --enable-ffplay \
    --enable-gmp \
    --enable-libgsm \
    --enable-alsa \
    --enable-libglslang \
    --enable-librsvg \
    --enable-ladspa \
    --enable-librubberband \
    --enable-libaom \
    --enable-libass \
    --enable-libbluray \
    --enable-libdav1d \
    --enable-libdrm \
    --enable-libfdk-aac \
    --enable-libfontconfig \
    --enable-libfreetype \
    --enable-libfribidi \
    --enable-libsvtav1 \
    --enable-libmp3lame \
    --enable-libnpp \
    --enable-libopus \
    --enable-librtmp \
    --enable-libsnappy \
    --enable-libspeex \
    --enable-libsrt \
    --enable-libtheora \
    --enable-libvorbis \
    --enable-libvpx \
    --enable-libwebp \
    --enable-libx264 \
    --enable-libx265 \
    --enable-libopenjpeg \
    --enable-libxcb \
    --enable-libxcb-shm \
    --enable-libxcb-xfixes \
    --enable-libxcb-shape \
    --enable-libxml2 \
    --enable-libxvid \
    --enable-libzimg \
    --enable-lzma \
    --enable-network \
    --enable-nvdec \
    --enable-nvenc \
    --enable-opencl \
    --enable-opengl \
    --enable-openssl \
    --enable-postproc \
    --enable-swresample \
    --enable-swscale \
    --enable-vaapi \
    --enable-vapoursynth \
    --enable-vdpau \
    --enable-zlib \
    --extra-cflags="-I/usr/local/cuda/include" \
    --nvccflags="-O3 -Xptxas -O3,-v -cudart=static -ccbin=/usr/bin/gcc-10 -Xcompiler -O3,-static,-march=native,-mtune=native,-static-libstdc++,-static-libgcc,-flto=16,-fuse-linker-plugin,-ffat-lto-objects,-fasynchronous-unwind-tables -Xlinker -flto=16,-fuse-linker-plugin,-ffat-lto-objects,-march=native,-mtune=native,-static-libstdc++,-static-libgcc,-static -Xarchive -flto=16,-fuse-linker-plugin,-ffat-lto-objects,-march=native,-mtune=native,-static-libstdc++,-static-libgcc,-static" \
    --extra-ldflags="-L/usr/nvidia/lib64 -L/usr/nvidia/lib64/vdpau -L/usr/lib64/dri -L/usr/local/cuda/lib64"
## make_prepend content
echo 'include $(SRC_PATH)/ffbuild/libffmpeg.mak' >> Makefile
## make_prepend end
## make_macro content
exit 1
make -j16 V=1 VERBOSE=1
## make_macro end

./ffmpeg -i '/opt/fprofile/harry.y4m' -y -vcodec h264_nvenc -preset slow -rc vbr_hq -cq 12 -qmin 12 -qmax 12 -f mp4 '/dev/null'
./ffmpeg -i '/opt/fprofile/harry2.y4m' -y -vcodec h264_nvenc -preset slow -rc vbr_hq -cq 12 -qmin 12 -qmax 12 -f mp4 '/dev/null'
./ffmpeg -i '/opt/fprofile/eyes.y4m' -y -vcodec h264_nvenc -preset slow -rc vbr_hq -cq 12 -qmin 12 -qmax 12 -f mp4 '/dev/null'
./ffmpeg -i '/opt/fprofile/allied.y4m' -y -vcodec h264_nvenc -preset slow -rc vbr_hq -cq 12 -qmin 12 -qmax 12 -f mp4 '/dev/null'
./ffmpeg -i '/opt/fprofile/gerra.y4m' -y -vcodec h264_nvenc -preset slow -rc vbr_hq -cq 12 -qmin 12 -qmax 12 -f mp4 '/dev/null'
timeout 16 ./ffplay -autoexit -t 00:00:14 -i '/opt/TDEP/downloads/rips/pp/Slim4K - Passionate FFM three-way fuck scene/slim4k-passionate-ffm-three-way-fuck-scene_1080p.mp4' -vcodec h264_cuvid
timeout 16 ./ffplay -autoexit -t 00:00:14 -i '/opt/TDEP/downloads/rips/pp/Slim4K - Passionate FFM three-way fuck scene/slim4k-passionate-ffm-three-way-fuck-scene_1080p.mp4'
timeout 16 ./ffplay -autoexit -t 00:00:14 -i '/opt/TDEP/stuff/videos/movies/Mad Max Fury Road 2015 UltraHD BluRay 2160p HEVC BT2020 TrueHD 7 1 Atmos-HDLeader/Mad.Max.Fury.Road.2015.UltraHD.BluRay.2160p.HEVC.BT2020.TrueHD 7.1.Atmos-HDLeader.mkv'
timeout 16 ./ffplay -autoexit -ss 01:00:00 -t 00:00:14 -i '/opt/TDEP/stuff/videos/movies/Midsommar.2019.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTG.mkv'
timeout 16 ./ffplay -autoexit -ss 01:00:00 -t 00:00:14 -i '/opt/TDEP/stuff/videos/movies/Midsommar.2019.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTG.mkv' -vcodec h264_cuvid
timeout 16 ./ffplay -autoexit -ss 00:40:00 -t 00:00:14 -i '/opt/TDEP/stuff/videos/movies/Parasite.Gisaengchung.2019.1080p.BluRay.FLAC.x264-BeiTai.mkv'
timeout 16 ./ffplay -autoexit -ss 00:40:00 -t 00:00:14 -i '/opt/TDEP/stuff/videos/movies/Parasite.Gisaengchung.2019.1080p.BluRay.FLAC.x264-BeiTai.mkv' -vcodec h264_cuvid
# xvfb-run --server-args="-screen 0 1920x1080x24+32"
make clean
echo USED > statuspgo
fi
if [ -f statuspgo ]; then
echo PGO Phase 2
export CFLAGS="${CFLAGS_USE}"
export CXXFLAGS="${CXXFLAGS_USE}"
export FFLAGS="${FFLAGS_USE}"
export FCFLAGS="${FCFLAGS_USE}"
export LDFLAGS="${LDFLAGS_USE}"
./configure \
    --prefix=/usr \
    --libdir=/usr/lib64 \
    --pkg-config-flags="--static" \
    --ar="/usr/bin/gcc-ar" \
    --nm="/usr/bin/gcc-nm" \
    --ranlib="/usr/bin/gcc-ranlib" \
    --cc=/usr/bin/gcc \
    --cxx=/usr/bin/g++ \
    --disable-shared \
    --disable-debug \
    --disable-avx512 \
    --disable-podpages \
    --disable-stripping \
    --disable-gnutls \
    --disable-runtime-cpudetect \
    --disable-libjack \
    --disable-cuda-llvm \
    --disable-libmfx \
    --disable-libv4l2 \
    --disable-libopencv \
    --cpu=native \
    --enable-optimizations \
    --enable-avx2 \
    --enable-doc \
    --enable-htmlpages \
    --enable-manpages \
    --enable-txtpages \
    --enable-static \
    --enable-pic \
    --enable-lto \
    --enable-libpulse \
    --enable-asm \
    --enable-pthreads \
    --enable-gpl \
    --enable-version3 \
    --enable-nonfree \
    --enable-hardcoded-tables \
    --enable-sdl2 \
    --enable-outdev=sdl2 \
    --enable-avcodec \
    --enable-avdevice \
    --enable-avfilter \
    --enable-avformat \
    --enable-avutil \
    --enable-dct \
    --enable-dwt \
    --enable-lsp \
    --enable-lzo \
    --enable-mdct \
    --enable-rdft \
    --enable-fft \
    --enable-faan \
    --enable-pixelutils \
    --enable-bzlib \
    --enable-cuda \
    --enable-cuda-nvcc \
    --enable-cuvid \
    --enable-error-resilience \
    --disable-safe-bitstream-reader \
    --enable-ffmpeg \
    --enable-ffnvcodec \
    --enable-ffplay \
    --enable-gmp \
    --enable-libgsm \
    --enable-alsa \
    --enable-libglslang \
    --enable-librsvg \
    --enable-ladspa \
    --enable-librubberband \
    --enable-libaom \
    --enable-libass \
    --enable-libbluray \
    --enable-libdav1d \
    --enable-libdrm \
    --enable-libfdk-aac \
    --enable-libfontconfig \
    --enable-libfreetype \
    --enable-libfribidi \
    --enable-libsvtav1 \
    --enable-libmp3lame \
    --enable-libnpp \
    --enable-libopus \
    --enable-librtmp \
    --enable-libsnappy \
    --enable-libspeex \
    --enable-libsrt \
    --enable-libtheora \
    --enable-libvorbis \
    --enable-libvpx \
    --enable-libwebp \
    --enable-libx264 \
    --enable-libx265 \
    --enable-libopenjpeg \
    --enable-libxcb \
    --enable-libxcb-shm \
    --enable-libxcb-xfixes \
    --enable-libxcb-shape \
    --enable-libxml2 \
    --enable-libxvid \
    --enable-libzimg \
    --enable-lzma \
    --enable-network \
    --enable-nvdec \
    --enable-nvenc \
    --enable-opencl \
    --enable-opengl \
    --enable-openssl \
    --enable-postproc \
    --enable-swresample \
    --enable-swscale \
    --enable-vaapi \
    --enable-vapoursynth \
    --enable-vdpau \
    --enable-zlib \
    --extra-cflags="-I/usr/local/cuda/include" \
    --nvccflags="-O3 -Xptxas -O3,-v -cudart=static -ccbin=/usr/bin/gcc-10 -Xcompiler -O3,-static,-march=native,-mtune=native,-static-libstdc++,-static-libgcc,-flto=16,-fuse-linker-plugin,-ffat-lto-objects,-fasynchronous-unwind-tables -Xlinker -flto=16,-fuse-linker-plugin,-ffat-lto-objects,-march=native,-mtune=native,-static-libstdc++,-static-libgcc,-static -Xarchive -flto=16,-fuse-linker-plugin,-ffat-lto-objects,-march=native,-mtune=native,-static-libstdc++,-static-libgcc,-static" \
    --extra-ldflags="-L/usr/nvidia/lib64 -L/usr/nvidia/lib64/vdpau -L/usr/lib64/dri -L/usr/local/cuda/lib64"
## make_prepend content
echo 'include $(SRC_PATH)/ffbuild/libffmpeg.mak' >> Makefile
## make_prepend end
## make_macro content
exit 1
make -j16 V=1 VERBOSE=1
## make_macro end
fi


%install
export SOURCE_DATE_EPOCH=1622807804
rm -rf %{buildroot}
%make_install
## install_append content
make libffmpeg V=1 VERBOSE=1
make install-libffmpeg V=1 VERBOSE=1 DESTDIR=%{buildroot}
## install_append end

%files
%defattr(-,root,root,-)
